services:
  routeroutside:
    build: ./routeroutsidedocker
    container_name: routeroutside
    hostname: routeroutside
    cap_add:
      - NET_ADMIN
    networks:
      OUTSIDE:
        ipv4_address: 69.69.69.68
      OUTSIDEandDMZ:
        ipv4_address: 192.168.69.68
    command: >-
      sh -c "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
      iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
      iptables -A FORWARD -i eth1 -j ACCEPT &&
      iptables -A FORWARD -i eth0 -j ACCEPT &&
      ip route add 172.16.0.0/29 via 192.168.69.69 &&
      tail -f /dev/null"
    tty: true

  attacker:
    build: ./attackerdocker
    container_name: attacker
    hostname: attacker
    cap_add:
      - NET_ADMIN
    networks:
      OUTSIDE:
        ipv4_address: 69.69.69.69
    command: >-
      sh -c "ip route del default &&
      ip route add default via 69.69.69.68 &&
      tail -f /dev/null"
    tty: true

  routerdmz:
    build: ./routerdmzdocker
    container_name: routerdmz
    hostname:  routerdmz
    networks:
      OUTSIDEandDMZ:
        ipv4_address: 192.168.69.69
      DMZ:
        ipv4_address: 172.16.0.1
    cap_add:
      - NET_ADMIN
    command: >-
      sh -c "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
      iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
      iptables -A FORWARD -i eth1 -j ACCEPT &&
      iptables -A FORWARD -i eth0 -j ACCEPT &&
      ip route add 69.69.69.64/29 via 192.168.69.68 &&
      tail -f /dev/null"
    tty: true

  db:
    build: ./dbdocker
    container_name: db
    hostname: db
    networks:
      DMZ:
        ipv4_address: 172.16.0.2
    ports:
      - "3306:3306"


  web:
    build: ./webappdocker
    container_name: web
    hostname:  wb
    networks:
      DMZ:
        ipv4_address: 172.16.0.3
    ports:
      - "8080:80"

networks:
  OUTSIDE:
    name: OUTSIDE
    driver: bridge
    ipam:
      config:
        - subnet: 69.69.69.64/29
          gateway: 69.69.69.70
    
  OUTSIDEandDMZ:
    name: OUTSIDEandDMZ
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.69.64/29
          gateway: 192.168.69.70
                  
  DMZ:
    name: DMZ
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/29
          gateway: 172.16.0.6
