# Download base image
FROM sebp/elk

# LABEL about the custom image
LABEL Maintainer="khoi, chandran"
LABEL Version="0.1"
LABEL Description="elk stack \
https://elk-docker.readthedocs.io/#building-the-image"

EXPOSE 5044
EXPOSE 5601
EXPOSE 9200